version: '3.7'
services:
  web:
    # build: .
    image: author-stylometry:bash
    container_name: raheem-web-compose
    ports:
      - "16112:80"
    environment:
      TZ: "Asia/Bangkok"
      FLASK_APP: "FLASK_APP=flask_app/app.py"
    depends_on: 
      - db
    links:
      - db
    restart: always
    tty: true
    # stdin_open: true
    # entrypoint:
    command: >
      bash -c "./preconfigure.sh cdba
      && python -m flask run -p 80 -h 0.0.0.0"

  db:
    image: postgres
    container_name: psql-compose
    environment:
      POSTGRES_PASSWORD: stylometry
    volumes:
    - /pgdata/:/var/lib/postgresql/10/main
    - /postgres/:/postgres/
    expose:
    - 5432
    restart: always
