version: '3'
services:
  db:
    container_name: db
    image: postgres:10
    deploy:
      restart_policy:
        condition: always 
    volumes:
      - /postgres/demo/:/docker-entrypoint-initdb.d/
      - /pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stylometry
      - POSTGRES_DB=stylometry

  stylometry-web:
    container_name: stylometry_web
    build: 
      context: .
      dockerfile: stylometry-web-dockerfile 
    links:
      - db
    ports:
      - 16112:80

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL: "admin@admin.com" 
      - PGADMIN_DEFAULT_PASSWORD: "1q2w3e4rj"
    links:
      - db
    ports:
      - 8080:80