version: '3.7'
services:
  web:
    # build: .
    image: author-stylometry
    container_name: raheem-web-compose
    ports:
      - "16112:80"
    environment:
      TZ: "Asia/Bangkok"
    depends_on: 
      - db
    links:
      - db
    restart: always

  db:
    image: postgres
    container_name: psql-compose
    environment:
      POSTGRES_PASSWORD: stylometry
    volumes:
    - $PWD/preconfigure.sh:/var/
    - /pgdata/:/var/lib/postgresql/10/main
    - /postgres/:/postgres/
    expose:
    - 5432
    restart: always
