version: '3.7'
services:
  web:
    # build: .
    image: author-stylometry
    container_name: raheem-web-compose
    ports:
      - "16112:80"
    environment:
      TZ: "Asia/Bangkok"
    depends_on: 
      - db
    links:
      - db
    restart: always

  db:
    image: postgres
    container_name: psql-compose
    environment:
      POSTGRES_PASSWORD: stylometry
      PARMDBUSER: postgres
      PARMNEWDBUSER: stylometry
      PARMNEWDBPW: $PARMNEWDBUSER
      PARMNEWDBNAME: $PARMNEWDBUSER

    command: 
      bash -c "su - $PARMDBUSER -c "psql -c \"CREATE USER $PARMNEWDBUSER WITH PASSWORD '$PARMNEWDBPW';\"" && su - $PARMDBUSER -c "psql -c \"CREATE DATABASE $PARMNEWDBNAME;\"" && su - $PARMDBUSER -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE $PARMNEWDBNAME TO $PARMNEWDBUSER;\"""
    # volumes:
    # - $PWD/preconfigure.sh:/var/
    # - /pgdata/:/var/lib/postgresql/10/main
    # - /postgres/:/postgres/
    expose:
    - 5432
    restart: always
