version: '3'
services:
  db:
    container_name: db
    image: postgres:10
    restart_policy:
      condition: always 
    volumes:
      - /postgres/demo:/docker-entrypoint-initdb.d/
      - /pgdata/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stylometry
      - POSTGRES_DB=stylometry

  stylometry-web:
    container_name: stylometry_web
    build: 
      context: .
      dockerfile: stylometry-web-dockerfile 
    links:
      - db
    ports:
      - 16112:80
