DROP TABLE IF EXISTS bigram_feature;
DROP TABLE IF EXISTS fact;
DROP TABLE IF EXISTS feature;
DROP TABLE IF EXISTS chapter;
DROP TABLE IF EXISTS paragraph;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS author;